#! /usr/bin/env python
#
# Support module generated by PAGE version 4.4.4
# In conjunction with Tcl version 8.6
#    Aug 09, 2015 12:13:46 PM
# HJK Aug 2015 This is the section where the button actions are implemented

import sys
#import TestSerialportOK1

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import comportconfig
import TestComport1
#import vrex_help
import comportconfig_support
import json
import serialport

def config_comport():
    print('TestComport1_support.config_comport')
   # vrex_help.create_Vrex_Help(root)
    comportconfig.create_ComportConfig(root)
#    comportconfig.localserialconfig = comportconfig.localserialconfig
#    print('new config',comportconfig.localserialconfig)
    sys.stdout.flush()
    root.title('Test_Comport1 ' + ',' + TestComport1.serialconfig['baudrate'] + ',' + TestComport1.serialconfig['comport'])

def ReadConfig1():
    f = open(comportconfig_support.filename, 'r')
    TestComport1.serialconfig = json.load(f)#[0]
    f.close()
#    TestComport1.root.title('Test_Comport1 ' + ',' + TestComport1.serialconfig['baudrate'] + ',' + TestComport1.serialconfig['comport'])
    print('config: ', TestComport1.serialconfig)

def connect_comport():
    #led_connect.configure(background="green")
    f = open(comportconfig_support.filename, 'r')
    TestComport1.serialconfig = json.load(f)#[0]
    f.close()
    print('settings',TestComport1.serialconfig)
    global w
    #w.
    print('TestComport1_support.connect_comport')
    root.title('Test_Comport1 ' + ',' + TestComport1.serialconfig['baudrate'] + ',' + TestComport1.serialconfig['comport'])
    sys.stdout.flush()

def send():
    print('TestComport1_support.send')
    sys.stdout.flush()

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    print('Init TestComport(support)')
    global ser1

    ser1 = serialport.tserial() #TestComport1.serialconfig['baudrate'], TestComport1.serialconfig['comport'])        # start serial port instance

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


